### ISSUE TITLE
When starting launch files via roslaunch "roslaunch px4 sfm.launch"- ERROR [px4] Error opening startup file, does not exist: etc/init.d/rcS

### ISSUE THREAD

**Issue by lulu402** [generalized-intelligence/GAAS#19]
**Followiing is the log:**

```
lulu@lulu-Vostro-3668:~$ roslaunch px4 sfm.launch
... logging to /home/lulu/.ros/log/3014fc68-5133-11e9-b6c3-3cf862c629e7/roslaunch-lulu-Vostro-3668-22089.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://lulu-Vostro-3668:45265/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/in/child_frame_id: base_link
 * /mavros/odometry/in/frame_id: odom
 * /mavros/odometry/in/frame_tf/body_frame_orientation: flu
 * /mavros/odometry/in/frame_tf/local_frame: local_origin_ned
 * /mavros/odometry/out/frame_tf/body_frame_orientation: frd
 * /mavros/odometry/out/frame_tf/local_frame: vision_ned
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682389136
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: map
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: map
 * /mavros/wheel_odometry/tf/send: True
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mavros (mavros/mavros_node)
    sitl (px4/px4)
    vehicle_spawn_lulu_Vostro_3668_22089_7992864178812158555 (gazebo_ros/spawn_model)

ROS_MASTER_URI=http://localhost:11311

process[sitl-1]: started with pid [22111]
INFO  [px4] Creating symlink /home/lulu/src/Firmware -> /home/lulu/.ros/etc
ERROR [px4] Error opening startup file, does not exist: etc/init.d/rcS
process[gazebo-2]: started with pid [22112]
process[gazebo_gui-3]: started with pid [22117]
process[vehicle_spawn_lulu_Vostro_3668_22089_7992864178812158555-4]: started with pid [22122]
================================================================================REQUIRED process [sitl-1] has died!
process has died [pid 22111, exit code 255, cmd /home/lulu/src/Firmware/build/px4_sitl_default/bin/px4 /home/lulu/src/Firmware /home/lulu/src/Firmware/posix-configs/SITL/init/ekf2/iris_stereo_rgb_gps __name:=sitl __log:=/home/lulu/.ros/log/3014fc68-5133-11e9-b6c3-3cf862c629e7/sitl-1.log].
log file: /home/lulu/.ros/log/3014fc68-5133-11e9-b6c3-3cf862c629e7/sitl-1*.log
Initiating shutdown!
================================================================================
process[mavros-5]: started with pid [22123]
[ INFO] [1553823913.485295611]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1553823913.486700214]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1553823913.486768007]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1553823913.486852512]: GCS bridge disabled
[ INFO] [1553823913.497186098]: Plugin 3dr_radio loaded
[ INFO] [1553823913.499117810]: Plugin 3dr_radio initialized
[ INFO] [1553823913.499216267]: Plugin actuator_control loaded
[ INFO] [1553823913.503447224]: Plugin actuator_control initialized
[ INFO] [1553823913.503537213]: Plugin altitude loaded
[ INFO] [1553823913.504373639]: Plugin altitude initialized
[ INFO] [1553823913.504442511]: Plugin command loaded
[ INFO] [1553823913.508733130]: Plugin command initialized
[ INFO] [1553823913.508822193]: Plugin ftp loaded
[mavros-5] killing on exit
[ERROR] [1553823913.512777707]: [registerService] Failed to contact master at [localhost:11311].  Retrying...
[vehicle_spawn_lulu_Vostro_3668_22089_7992864178812158555-4] killing on exit
[gazebo_gui-3] killing on exit
[sitl-1] killing on exit
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/gazebo_ros/spawn_model", line 21, in <module>
    import rospy, sys, os, time
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 54, in <module>
[gazebo-2] killing on exit
    import rospy.core
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/core.py", line 66, in <module>
    import rosgraph.roslogging
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/roslogging.py", line 41, in <module>
    import logging.config
  File "/usr/lib/python2.7/logging/config.py", line 489, in <module>
    class DictConfigurator(BaseConfigurator):
KeyboardInterrupt
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by Doodleshr** [comment]
`INFO  [px4] Creating symlink /home/lulu/src/Firmware -> /home/lulu/.ros/etc
ERROR [px4] Error opening startup file, does not exist: etc/init.d/rcS`

That's odd.
Check if ~/.ros/etc/init.d/rcS exists, otherwise you have to manually copy and paste it to corresponding folder.

**Comment by Doodleshr** [comment]
Close as stale, reopen if needed.
